image: mcr.microsoft.com/dotnet/sdk:5.0

stages:
    - build

variables:
    text: "Example.Test"

build:
    stage: build
    script:
        - "cd FamilyBudget.Entities"
        - "dotnet restore"
        - "dotnet build"
        - "cd ../FamilyBudget.Api"
        - "dotnet restore"
        - "dotnet build"
        - "cd ../Tests/FamilyBudget.Entities.Test"        
        - "dotnet test"
        - "cd ../FamilyBudget.Api.Test"
        - "dotnet test"

